package com.example.scaapi.api.controller;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;


public class TesteFuncionalTelaPosicao {
  private WebDriver driver;
  JavascriptExecutor js;
  private Map<String, Object> vars;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/chromedriver.exe");
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    driver = new ChromeDriver(options);

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @Test
  public void tF01ErroCriarPosicao() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    threadWait();
    driver.findElement(By.id(":r1:")).click();
    threadWait();
    driver.findElement(By.id(":r1:")).sendKeys("TesteFuncional");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r3:")).sendKeys("123456");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1ok7l8h-MuiStack-root > .MuiButtonBase-root:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)")).click();
    threadWait();
    driver.findElement(By.cssSelector(".bg-blue-600")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).sendKeys("Atacante");
    threadWait();
    driver.findElement(By.id(":r9:")).click();
    threadWait();
    driver.findElement(By.id(":r9:")).sendKeys("Meio");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":rb:")).sendKeys("ATA");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    driver.quit();
  }

  @Test
  public void tF02CadastroPosicao() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    threadWait();
    driver.findElement(By.id(":r1:")).click();
    threadWait();
    driver.findElement(By.id(":r1:")).sendKeys("TesteFuncional");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r3:")).sendKeys("123456");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1gilxof-MuiStack-root > .MuiButtonBase-root:nth-child(2)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)")).click();
    threadWait();
    driver.findElement(By.cssSelector(".bg-blue-600")).click();
    threadWait();
    js.executeScript("window.scrollTo(0,0)");
    threadWait();
    driver.findElement(By.id(":r5:")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).sendKeys("Lateral Direito");
    threadWait();
    driver.findElement(By.id(":r7:")).sendKeys("Zaga");
    threadWait();
    driver.findElement(By.id(":r9:")).sendKeys("Direita");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":rb:")).sendKeys("LA");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)")).click();
    threadWait();
    driver.quit();
  }

  @Test
  public void tF03ExcluirPosicao() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    threadWait();
    driver.findElement(By.id(":r1:")).click();
    threadWait();
    driver.findElement(By.id(":r1:")).sendKeys("TesteFuncional");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r3:")).sendKeys("123456");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1gilxof-MuiStack-root > .MuiButtonBase-root:nth-child(2)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)")).click();
    threadWait();
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(5) .bg-red-600")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(5) .bg-red-600"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.quit();
  }

  @Test
  public void tF04EditarPosicao() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    threadWait();
    driver.findElement(By.id(":r1:")).click();
    threadWait();
    driver.findElement(By.id(":r1:")).sendKeys("TesteFuncional");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r3:")).sendKeys("123456");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1gilxof-MuiStack-root > .MuiButtonBase-root:nth-child(2)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)")).click();
    threadWait();
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(1) .bg-gray-600")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).sendKeys("Lateral Esquerdo");
    threadWait();
    driver.findElement(By.id(":r7:")).click();
    threadWait();
    driver.findElement(By.id(":r7:")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.id(":r7:"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.doubleClick(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r7:")).sendKeys("Zaga");
    threadWait();
    driver.findElement(By.id(":rb:")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.id(":rb:"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.doubleClick(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":rb:")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":rb:")).sendKeys("LE");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)")).click();
    threadWait();
    driver.quit();
  }

  @Test
  public void tF05ErroEditarPosicao() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    threadWait();
    driver.findElement(By.id(":r1:")).click();
    threadWait();
    driver.findElement(By.id(":r1:")).sendKeys("TesteFuncional");
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r3:")).sendKeys("123456");
    threadWait();
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1gilxof-MuiStack-root > .MuiButtonBase-root:nth-child(2)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".stack-visao > .MuiButtonBase-root:nth-child(1)")).click();
    threadWait();
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(3) .bg-gray-600")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).click();
    threadWait();
    driver.findElement(By.id(":r5:")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.id(":r5:"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.doubleClick(element).perform();
      threadWait();
    }
    driver.findElement(By.id(":r5:")).sendKeys(" ");
    threadWait();
    driver.findElement(By.id(":r7:")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element).perform();
      threadWait();
    }
    driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)")).click();
    threadWait();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      threadWait();
      Actions builder = new Actions(driver);
      threadWait();
      builder.moveToElement(element, 0, 0).perform();
      threadWait();
      driver.quit();
    }
  }

  @After
  public void tearDown() {

  }


  public static void threadWait(int... argument) {
    int seconds = 1;

    if (argument != null && argument.length == 1) {
      seconds = argument[0];
    }

    try {
      Thread.sleep(seconds * 1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }

}
